import type { MonitorSnapshot, Worker } from "../types";

const now = Math.floor(Date.now() / 1000);

export const demoWorkers: Worker[] = [
  {
    id: "019f5ade-99ad-7ed1-b2f3-159136634cf7",
    threadId: "019f5ade-99ad-7ed1-b2f3-159136634cf7",
    hostId: "local",
    hostLabel: "This computer",
    hostKind: "local",
    parentId: null,
    displayName: "plow",
    threadName: "Polish the agent dashboard",
    repoName: "plow",
    repoPath: "/Users/demo/dev/plow",
    cwd: "/Users/demo/dev/plow",
    branch: "feature/farm-ui",
    model: "gpt-5.6-sol",
    reasoningEffort: "high",
    contextTokens: 86_240,
    contextWindow: 400_000,
    source: "cli",
    status: "running",
    activity: "plowing",
    updatedAt: now,
    startedAt: now - 743,
    attentionId: null,
  },
  {
    id: "01a067db-92ea-7081-88be-d1518179660e",
    threadId: "01a067db-92ea-7081-88be-d1518179660e",
    hostId: "local",
    hostLabel: "This computer",
    hostKind: "local",
    parentId: "019f5ade-99ad-7ed1-b2f3-159136634cf7",
    displayName: "plow",
    threadName: "Check the notification flow",
    repoName: "plow",
    repoPath: "/Users/demo/dev/plow",
    cwd: "/Users/demo/dev/plow",
    branch: "feature/farm-ui",
    model: "gpt-5.6-luna",
    reasoningEffort: "medium",
    contextTokens: 214_500,
    contextWindow: 400_000,
    source: "subAgent",
    status: "waitingApproval",
    activity: "watering",
    updatedAt: now - 12,
    startedAt: now - 328,
    attentionId: "demo-approval",
  },
  {
    id: "ssh:devbox:01a061d3-6d6c-7493-a8e0-bc1ee1b524fa",
    threadId: "01a061d3-6d6c-7493-a8e0-bc1ee1b524fa",
    hostId: "ssh:devbox",
    hostLabel: "devbox",
    hostKind: "ssh",
    parentId: null,
    displayName: "beacon-chain",
    threadName: "Investigate state recovery",
    repoName: "prysm",
    repoPath: "/Users/demo/dev/prysm",
    cwd: "/Users/demo/dev/prysm/beacon-chain",
    branch: "state-diff-cache",
    model: "gpt-5.6-sol",
    reasoningEffort: "xhigh",
    contextTokens: 361_200,
    contextWindow: 400_000,
    source: "vscode",
    status: "waitingInput",
    activity: "planting",
    updatedAt: now - 41,
    startedAt: now - 2230,
    attentionId: "demo-question",
  },
  {
    id: "01a06322-bd04-76d1-a7de-fea9326a85ce",
    threadId: "01a06322-bd04-76d1-a7de-fea9326a85ce",
    hostId: "local",
    hostLabel: "This computer",
    hostKind: "local",
    parentId: null,
    displayName: "consensus-specs",
    threadName: "Review consensus specification changes",
    repoName: "consensus-specs",
    repoPath: "/Users/demo/dev/consensus-specs",
    cwd: "/Users/demo/dev/consensus-specs",
    branch: "master",
    model: "gpt-5.6-sol",
    reasoningEffort: "high",
    contextTokens: 145_800,
    contextWindow: 400_000,
    source: "cli",
    status: "completed",
    activity: "harvesting",
    updatedAt: now - 180,
    startedAt: now - 4890,
    attentionId: "demo-complete",
  },
  {
    id: "ssh:devbox:01a062f3-0cc2-76d1-a399-b75bf204ee05",
    threadId: "01a062f3-0cc2-76d1-a399-b75bf204ee05",
    hostId: "ssh:devbox",
    hostLabel: "devbox",
    hostKind: "ssh",
    parentId: null,
    displayName: "infra",
    threadName: "Fix devnet bootstrap",
    repoName: "infra",
    repoPath: "/Users/demo/dev/infra",
    cwd: "/Users/demo/dev/infra",
    branch: "hoodi",
    model: "gpt-5.6-terra",
    reasoningEffort: "low",
    contextTokens: 72_100,
    contextWindow: 400_000,
    source: "cli",
    status: "failed",
    activity: "carrying",
    updatedAt: now - 74,
    startedAt: now - 903,
    attentionId: "demo-failed",
  },
];

export const demoSnapshot: MonitorSnapshot = {
  workers: demoWorkers,
  rateLimits: [
    {
      hostId: "local",
      hostLabel: "This computer",
      limits: [{
        limitId: "codex",
        limitName: null,
        primary: { usedPercent: 37, windowDurationMins: 300, resetsAt: now + 6_420 },
        secondary: { usedPercent: 81, windowDurationMins: 10_080, resetsAt: now + 345_600 },
      }],
    },
  ],
  connections: [
    {
      hostId: "local",
      hostLabel: "This computer",
      hostKind: "local",
      status: "connected",
      codexVersion: "demo",
      codexPath: "/Users/demo/.codex/packages/standalone/current/codex",
      message: "Browser preview — showing demo workers",
    },
    {
      hostId: "ssh:devbox",
      hostLabel: "devbox",
      hostKind: "ssh",
      status: "connected",
      codexVersion: "demo",
      codexPath: "codex",
      message: "Browser preview — watching devbox over SSH",
    },
  ],
};
